---

- name: Add Docker key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    validate_certs: yes
    state: present

- name: DEBUG repo
  shell: "echo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'"

- name: add Docker repo
  become: yes
  apt_repository:
    #repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
    validate_certs: yes

- name: Create docker group
  become: yes
  group:
    name: docker
    state: present

#- name: install docker-compose
  #become: yes
  #apt:
    #state: present
    #enablerepo: https://download.docker.com/linux/fedora/docker-ce.repo
    #name:
      #- docker-compose

- name: add to Docker group
  become: yes
  user:
    name: colin
    groups: docker
    append: yes

- name: Install Docker
  become: yes
  apt:
    pkg:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose
    update_cache: yes

- name: enable Docker service
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
