---

- name: Clone i3blocks
  git:
    repo: https://github.com/vivien/i3blocks.git
    dest: /tmp/i3blocks

- name: Run autogen for i3blocks
  shell: ./autogen.sh
  args:
    chdir: /tmp/i3blocks

- name: Run configure for i3blocks
  shell: ./configure
  args:
    chdir: /tmp/i3blocks

- name: Run make for i3blocks
  shell: make
  args:
    chdir: /tmp/i3blocks

- name: Run make install for i3blocks
  become: yes
  shell: make install
  args:
    chdir: /tmp/i3blocks

- name: Copy i3blocks config
  copy:
    mode: preserve
    src: i3blocks
    dest: "{{ lookup('env', 'HOME') }}/.config/"
