---
- name: Install the gpg key for nodejs
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the node v{{ nodejs_version }} repo
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install nodejs {{ nodejs_version }}
  become: yes
  apt:
    name: nodejs
    state: present


- name: Install yarn
  become: yes
  npm:
    name: yarn
    global: yes
    state: present
